export enum AuthInfraError {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  WEAK_PASSWORD = "WEAK_PASSWORD",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}